---

- apt: pkg=git
       state=installed
       update_cache=yes
       cache_valid_time=3600	

- git: repo={{ git_repo }}
       dest={{ app_path }}
       version={{ git_branch }}
       update=yes
  tags: git

# FIX - Check if apache service exists
#- name: reload apache
#  tags: git
#  service: name=apache2
#           state=reloaded
