"""Added account disabilty field

Revision ID: 114c4ec6dd6c
Revises: 430dc3c47bc
Create Date: 2016-01-04 10:25:58.538259

"""

# revision identifiers, used by Alembic.
revision = '114c4ec6dd6c'
down_revision = '430dc3c47bc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    enum = sa.Enum('none', 'hearing', 'mental', 'physical', 'visual', name='disability_types')
    enum.create(op.get_bind(), checkfirst=False)
    op.add_column(u'account', sa.Column('disability', enum, default='none', nullable=True))
    op.add_column(u'account', sa.Column('disability_info', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'account', 'disability_info')
    op.drop_column(u'account', 'disability')
    sa.Enum(name="disability_types").drop(op.get_bind(), checkfirst=False)
    ### end Alembic commands ###

