"""Updated visitor model

Revision ID: 150ae4290f1e
Revises: 4f935dc7403d
Create Date: 2016-06-22 16:25:24.649164

"""

# revision identifiers, used by Alembic.
revision = '150ae4290f1e'
down_revision = '4f935dc7403d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'visitor', sa.Column('badge_name', sa.Text(), nullable=True))
    op.add_column(u'visitor', sa.Column('phone', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'visitor', 'phone')
    op.drop_column(u'visitor', 'badge_name')
    ### end Alembic commands ###
