"""Added paypal support

Revision ID: 18fcdf2142e1
Revises: 42a5cd66028
Create Date: 2016-03-04 11:26:09.666905

"""

# revision identifiers, used by Alembic.
revision = '18fcdf2142e1'
down_revision = '42a5cd66028'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'payment', sa.Column('pp_correlation_id', sa.Text(), nullable=True))
    op.add_column(u'payment', sa.Column('pp_invnum', sa.String(length=32), nullable=True))
    op.add_column(u'payment', sa.Column('pp_token', sa.Text(), nullable=True))
    op.add_column(u'transition', sa.Column('pp_payload', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'transition', 'pp_payload')
    op.drop_column(u'payment', 'pp_token')
    op.drop_column(u'payment', 'pp_invnum')
    op.drop_column(u'payment', 'pp_correlation_id')
    ### end Alembic commands ###
