"""Updated account model

Revision ID: 1c02443c8bed
Revises: 4dd90f59542d
Create Date: 2016-01-25 09:58:14.360721

"""

# revision identifiers, used by Alembic.
revision = '1c02443c8bed'
down_revision = '4dd90f59542d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    enum = sa.Enum('person', 'company', name='account_types')
    enum.create(op.get_bind(), checkfirst=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'account', sa.Column('document_type', postgresql.ENUM(u'cpf', u'cnpj', u'passport', name='document_types'), autoincrement=False, nullable=True))
    op.drop_column(u'account', 'type')
    sa.Enum(name="account_types").drop(op.get_bind(), checkfirst=False)
    ### end Alembic commands ###
