"""Added a new role and permission system

Revision ID: 2ae42c9d3801
Revises: a78fa8b62a2
Create Date: 2016-08-04 07:51:52.591407

"""

# revision identifiers, used by Alembic.
revision = '2ae42c9d3801'
down_revision = 'a78fa8b62a2'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts_roles',
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], )
    )
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('roles_accounts')
    op.drop_column(u'account', 'role')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'account', sa.Column('role', postgresql.ENUM(u'user', u'operator', u'admin', u'corporate', u'foreign', u'employee', u'cashier', name='account_roles'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'account', type_='unique')
    op.create_table('roles_accounts',
    sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], [u'account.id'], name=u'roles_accounts_account_id_fkey'),
    sa.ForeignKeyConstraint(['role_id'], [u'role.id'], name=u'roles_accounts_role_id_fkey')
    )
    op.drop_table('permission')
    op.drop_table('accounts_roles')
    ### end Alembic commands ###

