"""Added start and end date to promocodes

Revision ID: 34b8c096e9b5
Revises: 2ae42c9d3801
Create Date: 2016-08-22 09:47:35.047331

"""

# revision identifiers, used by Alembic.
revision = '34b8c096e9b5'
down_revision = '2ae42c9d3801'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'promocode', sa.Column('end_at', sa.Date(), nullable=True))
    op.add_column(u'promocode', sa.Column('start_at', sa.Date(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'promocode', 'start_at')
    op.drop_column(u'promocode', 'end_at')
    ### end Alembic commands ###
