"""Added membership and student_doc

Revision ID: 3515f5a108f7
Revises: 5849a77f3a4b
Create Date: 2016-01-19 09:22:55.089438

"""

# revision identifiers, used by Alembic.
revision = '3515f5a108f7'
down_revision = '5849a77f3a4b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'account', sa.Column('membership', sa.Boolean(), nullable=True))
    op.add_column(u'account', sa.Column('student_document', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'account', 'student_document')
    op.drop_column(u'account', 'membership')
    ### end Alembic commands ###
