"""IamAWizardPart2

Revision ID: 353a0bbf0000
Revises: 3fb36e9787bf
Create Date: 2016-04-05 20:48:10.794447

"""

# revision identifiers, used by Alembic.
revision = '353a0bbf0000'
down_revision = '3fb36e9787bf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
