"""Improved purchase model

Revision ID: 3aec24d1b31a
Revises: 3cc068645e81
Create Date: 2016-02-05 10:58:36.293380

"""

# revision identifiers, used by Alembic.
revision = '3aec24d1b31a'
down_revision = '3cc068645e81'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'purchase', sa.Column('amount', sa.Float(precision=3), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'purchase', 'amount')
   ### end Alembic commands ###
