"""Added receive_email

Revision ID: 3cc068645e81
Revises: f48b0d8af00
Create Date: 2016-01-27 09:42:22.310362

"""

# revision identifiers, used by Alembic.
revision = '3cc068645e81'
down_revision = 'f48b0d8af00'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'account', sa.Column('receive_emails', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'account', 'receive_emails')
    ### end Alembic commands ###

