"""Added payment_days

Revision ID: 42a5cd66028
Revises: 3f90a28ff0f0
Create Date: 2016-02-29 16:28:07.905120

"""

# revision identifiers, used by Alembic.
revision = '42a5cd66028'
down_revision = '3f90a28ff0f0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'payment', 'bo_due_date')
    op.add_column(u'product', sa.Column('payment_days', sa.Numeric(), nullable=True))
    op.add_column(u'purchase', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column(u'payment', sa.Column('due_date', sa.Date(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'purchase', 'due_date')
    op.drop_column(u'product', 'payment_days')
    op.drop_column(u'payment', 'due_date')
    op.add_column(u'payment', sa.Column('bo_due_date', sa.DATE(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
