"""Added address_state and address_neighborhood fields

Revision ID: 49164cd7c07
Revises: 114c4ec6dd6c
Create Date: 2016-01-05 17:08:25.538487

"""

# revision identifiers, used by Alembic.
revision = '49164cd7c07'
down_revision = '114c4ec6dd6c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'buyer', sa.Column('address_neighborhood', sa.Text(), nullable=True))
    op.add_column(u'buyer', sa.Column('address_state', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'buyer', 'address_state')
    op.drop_column(u'buyer', 'address_neighborhood')
    ### end Alembic commands ###
