"""Fixed unique survey constraint

Revision ID: 4dd90f59542d
Revises: 335d1b6ab5d0
Create Date: 2016-01-21 09:38:07.798163

"""

# revision identifiers, used by Alembic.
revision = '4dd90f59542d'
down_revision = '335d1b6ab5d0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('UK_account_survey_question', 'survey_answer', ['account_id', 'survey', 'question'])
    op.drop_constraint(u'UK_account_question', 'survey_answer', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'UK_account_question', 'survey_answer', ['account_id', 'question'])
    op.drop_constraint('UK_account_survey_question', 'survey_answer', type_='unique')
    ### end Alembic commands ###
