"""Changed payment date to  due date

Revision ID: 4f89d195687c
Revises: 6312998a103
Create Date: 2016-03-30 11:13:07.971857

"""

# revision identifiers, used by Alembic.
revision = '4f89d195687c'
down_revision = '6312998a103'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'product', sa.Column('due_date', sa.Date(), nullable=True))
    op.drop_column(u'product', 'payment_days')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'product', sa.Column('payment_days', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_column(u'product', 'due_date')
    ### end Alembic commands ###
