"""Added a few attributes to account

Revision ID: 4f935dc7403d
Revises: 353a0bbf0000
Create Date: 2016-06-22 10:45:59.707072

"""

# revision identifiers, used by Alembic.
revision = '4f935dc7403d'
down_revision = '353a0bbf0000'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'account', sa.Column('employer_activity', sa.Text(), nullable=True))
    op.add_column(u'account', sa.Column('employer_size', sa.Text(), nullable=True))
    op.add_column(u'account', sa.Column('occupation_decision_power', sa.Text(), nullable=True))
    op.add_column(u'account', sa.Column('occupation_position', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'account', 'occupation_position')
    op.drop_column(u'account', 'occupation_decision_power')
    op.drop_column(u'account', 'employer_size')
    op.drop_column(u'account', 'employer_activity')
    ### end Alembic commands ###
