"""Added document_file_hash and extra document to buyer

Revision ID: 5833b0796126
Revises: 4f6fb6cd9a86
Create Date: 2016-03-08 15:06:10.699173

"""

# revision identifiers, used by Alembic.
revision = '5833b0796126'
down_revision = '4f6fb6cd9a86'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'buyer', sa.Column('document_file_hash', sa.String(length=80), nullable=True))
    op.add_column(u'buyer', sa.Column('extra_document', sa.String(length=80), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'buyer', 'extra_document')
    op.drop_column(u'buyer', 'document_file_hash')
    ### end Alembic commands ###
