"""Updated account fields

Revision ID: 5849a77f3a4b
Revises: 49164cd7c07
Create Date: 2016-01-10 23:56:33.479052

"""

# revision identifiers, used by Alembic.
revision = '5849a77f3a4b'
down_revision = '49164cd7c07'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    enum = sa.Enum('cpf', 'cnpj', 'passport', name='document_types')
    enum.create(op.get_bind(), checkfirst=False)
    op.add_column(u'account', sa.Column('address_extra', sa.Text(), nullable=True))
    op.add_column(u'account', sa.Column('address_neighborhood', sa.Text(), nullable=True))
    op.add_column(u'account', sa.Column('address_number', sa.Text(), nullable=True))
    op.add_column(u'account', sa.Column('address_state', sa.Text(), nullable=True))
    op.add_column(u'account', sa.Column('address_street', sa.Text(), nullable=True))
    op.add_column(u'account', sa.Column('address_zipcode', sa.Text(), nullable=True))
    op.add_column(u'account', sa.Column('born_date', sa.Date(), nullable=True))
    op.add_column(u'account', sa.Column('dirty', sa.Boolean(), nullable=True))
    op.add_column(u'account', sa.Column('document_type', enum, nullable=True))
    op.add_column(u'account', sa.Column('education', sa.Text(), nullable=True))
    op.add_column(u'account', sa.Column('occupation', sa.Text(), nullable=True))
    op.add_column(u'account', sa.Column('sex', sa.String(length=1), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'account', 'sex')
    op.drop_column(u'account', 'occupation')
    op.drop_column(u'account', 'education')
    op.drop_column(u'account', 'document_type')
    op.drop_column(u'account', 'dirty')
    op.drop_column(u'account', 'born_date')
    op.drop_column(u'account', 'address_zipcode')
    op.drop_column(u'account', 'address_street')
    op.drop_column(u'account', 'address_state')
    op.drop_column(u'account', 'address_number')
    op.drop_column(u'account', 'address_neighborhood')
    op.drop_column(u'account', 'address_extra')
    sa.Enum(name="document_types").drop(op.get_bind(), checkfirst=False)
    ### end Alembic commands ###
