"""Added max_purchases to product model

Revision ID: 9388cc1122c
Revises: 5833b0796126
Create Date: 2016-03-09 10:53:12.766482

"""

# revision identifiers, used by Alembic.
revision = '9388cc1122c'
down_revision = '5833b0796126'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'product', sa.Column('max_purchases', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'product', 'max_purchases')
    ### end Alembic commands ###
