"""Added promocode_product_id

Revision ID: cbd0f6a4415
Revises: d545899a6ca
Create Date: 2016-04-04 14:25:24.419725

"""

# revision identifiers, used by Alembic.
revision = 'cbd0f6a4415'
down_revision = 'd545899a6ca'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'product', sa.Column('promocode_product_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_promocode_product', 'product', 'product', ['promocode_product_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_promocode_product', 'product', type_='foreignkey')
    op.drop_column(u'product', 'promocode_product_id')
    ### end Alembic commands ###
