"""Allow user share his information

Revision ID: e7254f01f08
Revises: 150ae4290f1e
Create Date: 2016-07-08 08:50:49.398692

"""

# revision identifiers, used by Alembic.
revision = 'e7254f01f08'
down_revision = '150ae4290f1e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'account', sa.Column('inform', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'account', 'inform')
    ### end Alembic commands ###
