"""empty message

Revision ID: f48b0d8af00
Revises: 1c02443c8bed
Create Date: 2016-01-25 10:22:12.080262

"""

# revision identifiers, used by Alembic.
revision = 'f48b0d8af00'
down_revision = '1c02443c8bed'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'account', sa.Column('type', sa.Enum('person', 'company', name='account_types'), nullable=True))
    op.drop_column(u'account', 'document_type')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'account', sa.Column('document_type', postgresql.ENUM(u'cpf', u'cnpj', u'passport', name='document_types'), autoincrement=False, nullable=True))
    op.drop_column(u'account', 'type')
    ### end Alembic commands ###
