---

- hosts: production
  sudo: true
  roles:
    - server
    - git-down
    - certificates
    - recordings
    - database
    - segue
    - DavidWittman.redis

  vars_files:
    - secret/production.yml
