---

- hosts: vagrant
  sudo: True
  roles:
    - accelerate

- hosts: vagrant
  sudo: true
  accelerate: true
  roles:
    - nodesource.node
    - realtime
    - database
    - segue
    - server

  vars_files:
    - secret/vagrant.yml
