---

- hosts: vagrant
  sudo: True
  roles:
    - accelerate

- hosts: vagrant
  sudo: true
  accelerate: true
  roles:
    - database
    - segue
    - server
    - DavidWittman.redis

  vars_files:
    - secret/vagrant.yml
